# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2022 Plata Hill <plata.hill@kdemail.net>
---
app-id: org.kde.telly-skout
runtime: org.kde.Platform
runtime-version: 6.10
sdk: org.kde.Sdk
command: telly-skout
copy-icon: true
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  - --share=network
  - --share=ipc
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
cleanup:
  - /include
  - /lib/cmake
  - /lib/libexec
  - /mkspecs
  - /etc/xdg/*categories
  - /share/qlogging-categories5
modules:
  - name: telly-skout
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: '.'
