# SPDX-FileCopyrightText: 2022 Plata Hill <plata.hill@kdemail.net>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on':
      - '@all'
    require:
      frameworks/extra-cmake-modules: '@stable'
      frameworks/kcoreaddons: '@stable'
      frameworks/kconfig: '@stable'
      frameworks/ki18n: '@stable'
      frameworks/kirigami: '@stable'
  - 'on':
      - FreeBSD
      - Linux
      - Windows
    require:
      frameworks/kcrash: '@stable'

Options:
  require-passing-tests-on:
    - '@all'
